---
title: "Ozone Krige Prediciton"
subtitle: "Variable: Elevation"
author: "Ryan Erickson"
date: "2023-05-19"
output: pdf_document
---

# Data Prep and Display

```{r, message=FALSE, warning=FALSE}
source("R/ozone_krige.R")
# get elevation from DEM data. 
# 1. Ozone with Temperature
# 2. Ozone with distance to nearest A1 road
# 3. Ozone with total length of all A1 roads within 500 m
# 4. Ozone with temperature and RH
# 5. Ozone with temperature and distance to nearest A1 road
# 6. Ozone with temperature and elevation
# 7. Ozone with temperature and elevation and distance to nearest A1 road.

path_to_data_folder="data/krige_data/"
added_tiffs_list = list.files(path_to_data_folder)
# added_tiffs_list -> for identifying correct tiffs
o3_data_to_add = raster(paste0(path_to_data_folder,added_tiffs_list[3]))
added_data_projected = raster::projectRaster(o3_data_to_add, crs=prg)
o3_projected$elev=round(raster::extract(added_data_projected,o3_projected),2)

plot(added_data_projected, main="Elevation")
plot(o3_projected, add=TRUE)
plot(den_projected, add=TRUE)

# head(cbind(o3_projected$site_name,o3_projected$elev))
# join elevation column back to o3_projected
# o3_projected = merge(x=o3_projected,y=o3_elevs,by="site_name", duplicateGeoms = TRUE)
#o3_projected
year_o3 = as.data.frame(o3_projected)
year_o3 = year_o3 %>% 
  dplyr::select(c("site_name","elev","long","lat"),everything())

# use to create dataframe of specific months, ex below is summer
summer_o3 = year_o3 %>%
  dplyr::select(contains(c("site_name","lat","long","elev","Apr","May","Jun","Jul","Aug","Sep","Oct"))) %>% 
  dplyr::select(-contains(c("2021", "2022"))) #select only for 2018,2019, 2020

# preview data
# summer_o3
```

# Co- Kriging Semivariograms - Elevation

Plots predict for the following April 2018, April 2019, April 2020, May 2018, May 2019, May 2020, June 2018...etc. October 2020.

```{r, message=FALSE, warning=FALSE}
# # create months as spatial object
coordinates(summer_o3) = c('long', 'lat')
proj4string(summer_o3) = CRS(prg)
summer_o3 = spTransform(summer_o3, CRS(prg))
# head(summer_o3,3)

# create list of column month names 
cols = names(summer_o3)[-c(1:2)]

# create empty list to store variograms
vgms = vector("list")

variogram()

# loop thru columns
# var name = name of each month
# reformulate to do month~1 -> this is oridinary/simple kriging
# store in vgms, -> add models
for(i in seq_along(cols)) {
  var_name = cols[i]
  v = autofitVariogram(reformulate("elev",var_name),summer_o3)
  vgms[[i]] = v
}
# vgms

for(i in seq_along(cols)) {
 plot(vgms[[i]])
}
```

# Simple Kriging Semivariograms - Comparison
Plots predict in the same sequence (April 2018, April 2019, April 2020, May 2018, May 2019, May 2020, June 2018...etc. October 2020).

```{r, message=FALSE, warning=FALSE}
# create empty list to store variograms
vgms2 = vector("list")

# loop thru columns
# var name = name of each month
# reformulate to do month~1 -> this is oridinary/simple kriging
# store in vgms, -> add models
for(i in seq_along(cols)) {
  var_name = cols[i]
  v = autofitVariogram(reformulate("1",var_name),summer_o3)
  vgms2[[i]] = v
}
# vgms

for(i in seq_along(cols)) {
 plot(vgms2[[i]])
}
# semi-varigram formula : 1/2n*sum[Z(u)-Z(u+h)]2
# n=number of pairs
# Z(u) = data
# Z(h) = lag data
dists <- dist(summer_o3[,2:3]) 

A <- attr(dists, "Size")
B = sequence(A)
row = B[unlist(lapply(sequence(A)[-1], function(x) x:A))]
col = rep(B[-length(B)], (length(B)-1):1)
value = as.vector(dists)
df = data.frame(col,row,value)
df$sq_diff=NA

df[1:7,]$sq_diff=(var_df[1,]$elev-var_df$elev[2:8])^2
df[8:13,]$sq_diff=(var_df[2,]$elev-var_df$elev[3:8])^2
df[14:18,]$sq_diff=(var_df[3,]$elev-var_df$elev[4:8])^2
df[19:22,]$sq_diff=(var_df[4,]$elev-var_df$elev[5:8])^2
df[23:25,]$sq_diff=(var_df[5,]$elev-var_df$elev[6:8])^2
df[26:27,]$sq_diff=(var_df[6,]$elev-var_df$elev[7:8])^2
df[28,]$sq_diff=(var_df[7,]$elev-var_df$elev[8])^2
plot(df$value,df$sq_diff)

```