---
title: "Rough_Draft_Report"
author: "Ryan Erickson"
date: "2023-06-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries Used

```{r}
# This is for downloading and processing the .nc files from GridMET: https://www.climatologylab.org/gridmet.html
# I used the second option '2. Create "wget script" -> might take this out
library(raster)
library(rasterVis)
library(ncdf4)
library(lattice)
library(stringr)
library(raster)
library(sf)
library(dplyr)
```

#### Special R Document 

\begin{center}
Here I'm using `rsource()` to load the R script where I created/cleaned the guage locations
\end{center}

```{r}
source("ozone_krige.R") #need change for mac when applicable
```



```{r}
# Necessary Folders
path_start = "data/" #change as needed - I set my project directory to the same folder as the data
# Data: http://thredds.northwestknowledge.net:8080/thredds/reacch_climate_MET_aggregated_catalog.html
path_to_cropped_data = "final_data/"  #need change for mac when applicable
data_list = list.files(path_start)
co_data_list = list.files(path_to_cropped_data)
# Random Forest Variables
# Spatial Variables:

### Dist to nearest Road -  
getting_folders = grep("co_roads_2019", co_data_list, value = T)
road_shp_file = "co_roads_2019.shp"
path_to_roads = paste0(path_to_cropped_data,getting_folders,"/")
# C = County

# I = Interstate
# M = Common Name
# O = Other
# S = State recognized
# U = U.S.
roads_shp = st_read(paste0(path_to_roads,road_shp_file))
roads_transformed = st_transform(roads_shp,crs=CRS(prg))
roads_projected = as(roads_transformed, "Spatial")
dist2road = o3_projected$dist2road[1]=round(rgeos::gDistance(roads_projected,o3_projected[1,]),2)
for(i in 2:nrow(o3_projected)){
  dist2road=c(dist2road,round(rgeos::gDistance(roads_projected,o3_projected[i,]),2))
}
o3_projected$dist2road=dist2road

# sum of roads in 500m buffer - 
add_road_buffer = read_csv("final_data/roads_in_500m_buffer.csv")[,c(2,4)] %>% 
  filter(site_name != "Aspen Park" & site_name != "Evergreen" & site_name !="Welch")
names(add_road_buffer) = c("site_name","road_length")
add_road_buffer$road_length=ifelse(is.na(add_road_buffer$road_length),0,add_road_buffer$road_length)
o3_projected = merge(x=o3_projected,y=add_road_buffer,by="site_name")

# elevation
elevation_to_add = raster("final_data/elevation.tiff")
elevation_projected = raster::projectRaster(elevation_to_add, crs=prg)
o3_projected$elev=round(raster::extract(elevation_projected,o3_projected),2)

#data frame creation
year_o3 = as.data.frame(o3_projected) %>% 
  dplyr::select(c("site_name","elev","dist2road","road_length","lat","long"),everything())

# use to create dataframe of specific months, ex below is summer
summer_o3 = year_o3 %>%
  dplyr::select(contains(c("site_name","lat","long","elev","dist2road","road_length","Apr","May","Jun","Jul","Aug","Sep","Oct"))) %>% 
  pivot_longer(cols = contains(c("Apr","May","Jun","Jul","Aug","Sep","Oct")), names_to = "date", values_to = "mda8")
# preview data
#summer_o3

# lat 
summer_o3$lat

# long
summer_o3$long

# Temporal Variables: -> Can't do dummy variables until pivoted? (easiest method off top of head)
# monthly dummy variable -
# make a 1 for each month of interest and a 0 for other months
# yearly dummy variable -
# make a 1 for each year of interest and a 0 for other years

# Spatio-Temporal Variables:
new_path = "final_data/Monthly/"
monthly_path = list.files(paste0(new_path))
max_rh_files=grep("rmax_",monthly_path, value = T)
max_temp_files=grep("tmmx_",monthly_path, value = T)
max_precip_files=grep("pr_",monthly_path, value = T)
renameing_convention = c(paste0(month.abb,".",2017),
                        paste0(month.abb,".",2018),
                        paste0(month.abb,".",2019),
                        paste0(month.abb,".",2020),
                        paste0(month.abb,".",2021),
                        paste0(month.abb,".",2022))
coordinates(summer_o3) = c('long', 'lat')
proj4string(summer_o3) = CRS(SRS_string = prg)
AE=summer_o3[which(summer_o3$site_name=="Aurora East"),]
BR=summer_o3[which(summer_o3$site_name=="Boulder Reservoir"),]
DC=summer_o3[which(summer_o3$site_name=="Denver - Camp"),]
HR=summer_o3[which(summer_o3$site_name=="Highland Reservoir"),]
LA=summer_o3[which(summer_o3$site_name=="La Casa"),]
NREL=summer_o3[which(summer_o3$site_name=="National Renewable Energy Labs - Nrel"),]
RF=summer_o3[which(summer_o3$site_name=="Rocky Flats-N"),]
WY=summer_o3[which(summer_o3$site_name=="Welby"),]

# yearly NDVI - Average NDVI 500m buffer - need buffer data is ready
co_poin

################################################# Monthly total precip

max_precip_to_add = stack(paste0(new_path,max_precip_files)) # create stack of raster bricks (each "stack" is a year, each "brick" is a month)
#plots
# plot(max_precip_to_add$tmmx_2017_monthly_avg_1.1, main="Precipitation for Jan 2017")
max_precip_projected = raster::projectRaster(max_precip_to_add, crs=prg)
names(max_precip_projected) = renameing_convention
#plots: after running names() (above code)
# plot(max_precip_projected$Jan.2017, main="Precipitation for Jan 2017")
summer_max_precip =max_precip_projected[[c(grep("2018", names(max_precip_projected)),
                                               grep("2019", names(max_precip_projected)),
                                               grep("2020", names(max_precip_projected)),
                                               grep("2021", names(max_precip_projected)),
                                               grep("2022", names(max_precip_projected)))]]
summer_max_precip =summer_max_precip[[c(grep("Apr", names(summer_max_precip)),
                                      grep("May", names(summer_max_precip)),
                                      grep("Jun", names(summer_max_precip)),
                                      grep("Jul", names(summer_max_precip)),
                                      grep("Aug", names(summer_max_precip)),
                                      grep("Sep", names(summer_max_precip)),
                                      grep("Oct", names(summer_max_precip)))]]

################################################## Monthly max temp -> rounded K to F formula just in case: 1.8*(K-273) + 32

max_temperature_to_add = stack(paste0(new_path,max_temp_files)) # create stack of raster bricks (each "stack" is a year, each "brick" is a month)
#plots
# plot(max_temperature_to_add$tmmx_2017_monthly_avg_1.1, main="Temperature for Jan 2017")

max_temperature_projected = raster::projectRaster(max_temperature_to_add, crs=prg)
names(max_temperature_projected) = renameing_convention
#plots: after running names() (above code)
# plot(max_temperature_projected$Jan.2017, main="Temperature for Jan 2017")
summer_max_temps =max_temperature_projected[[c(grep("2018", names(max_temperature_projected)),
                                  grep("2019", names(max_temperature_projected)),
                                  grep("2020", names(max_temperature_projected)),
                                  grep("2021", names(max_temperature_projected)),
                                  grep("2022", names(max_temperature_projected)))]]
summer_max_temps =summer_max_temps[[c(grep("Apr", names(summer_max_temps)),
            grep("May", names(summer_max_temps)),
            grep("Jun", names(summer_max_temps)),
            grep("Jul", names(summer_max_temps)),
            grep("Aug", names(summer_max_temps)),
            grep("Sep", names(summer_max_temps)),
            grep("Oct", names(summer_max_temps)))]]

##################################################  Monthly RH 

max_rh_to_add = stack(paste0(new_path,max_rh_files)) # create stack of raster bricks (each "stack" is a year, each "brick" is a month)
#plots
# plot(max_rh_to_add$tmmx_2017_monthly_avg_1.1, main="Relative Humidity for Jan 2017")
max_rh_projected = raster::projectRaster(max_rh_to_add, crs=prg)
names(max_rh_projected) = renameing_convention
#plots: after running names() (above code)
# plot(max_rh_projected$Jan.2017, main="Relative Humidity for Jan 2017")
summer_max_rh =max_rh_projected[[c(grep("2018", names(max_rh_projected)),
                                           grep("2019", names(max_rh_projected)),
                                           grep("2020", names(max_rh_projected)),
                                           grep("2021", names(max_rh_projected)),
                                           grep("2022", names(max_rh_projected)))]]
summer_max_rh =summer_max_rh[[c(grep("Apr", names(summer_max_rh)),
                                        grep("May", names(summer_max_rh)),
                                        grep("Jun", names(summer_max_rh)),
                                        grep("Jul", names(summer_max_rh)),
                                        grep("Aug", names(summer_max_rh)),
                                        grep("Sep", names(summer_max_rh)),
                                        grep("Oct", names(summer_max_rh)))]]
##################################################  Exposure Assignment
for(i in 1:nrow(AE)) {
  AE$tmax[i] = extract(summer_max_temps[[i]],AE[i,])
  AE$rhmax[i] = extract(summer_max_rh[[i]],AE[i,])
  AE$pmax[i] = extract(summer_max_precip[[i]],AE[i,])
}
for(i in 1:nrow(BR)) {
  BR$tmax[i] = extract(summer_max_temps[[i]],BR[i,])
  BR$rhmax[i] = extract(summer_max_rh[[i]],BR[i,])
  BR$pmax[i] = extract(summer_max_precip[[i]],BR[i,])
}
for(i in 1:nrow(DC)) {
  DC$tmax[i] = extract(summer_max_temps[[i]],DC[i,])
  DC$rhmax[i] = extract(summer_max_rh[[i]],DC[i,])
  DC$pmax[i] = extract(summer_max_precip[[i]],DC[i,])
}
for(i in 1:nrow(HR)) {
  HR$tmax[i] = extract(summer_max_temps[[i]],HR[i,])
  HR$rhmax[i] = extract(summer_max_rh[[i]],HR[i,])
  HR$pmax[i] = extract(summer_max_precip[[i]],HR[i,])
}
for(i in 1:nrow(LA)) {
  LA$tmax[i] = extract(summer_max_temps[[i]],LA[i,])
  LA$rhmax[i] = extract(summer_max_rh[[i]],LA[i,])
  LA$pmax[i] = extract(summer_max_precip[[i]],LA[i,])
}
for(i in 1:nrow(NREL)) {
  NREL$tmax[i] = extract(summer_max_temps[[i]],NREL[i,])
  NREL$rhmax[i] = extract(summer_max_rh[[i]],NREL[i,])
  NREL$pmax[i] = extract(summer_max_precip[[i]],NREL[i,])
}
for(i in 1:nrow(RF)) {
  RF$tmax[i] = extract(summer_max_temps[[i]],RF[i,])
  RF$rhmax[i] = extract(summer_max_rh[[i]],RF[i,])
  RF$pmax[i] = extract(summer_max_precip[[i]],RF[i,])
}
for(i in 1:nrow(WY)) {
  WY$tmax[i] = extract(summer_max_temps[[i]],WY[i,])
  WY$rhmax[i] = extract(summer_max_rh[[i]],WY[i,])
  WY$pmax[i] = extract(summer_max_precip[[i]],WY[i,])
}

rbind(AE,BR,DC,HR,LA,NREL,RF,WY)
ggs = as.data.frame(rbind(AE,BR,DC,HR,LA,NREL,RF,WY))
ggs %>% 
  group_by(site_name) %>% 
  slice_head(n=1)

# Monthly mode of wind direction -> omiting this but not deleting because I may come back to it

# Still Need: RF Model, "Leave one out" cross validation
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
